import:
    - { file: "parameters.yml" }
    - { file: "services.yml" }
    - { file: "framework.yml" }

parameters:
    locale: "%locale%"


    php:
        date.timezone: Europe/Prague
        # zlib.output_compression: yes
    
config:
    debug_profile:  disable

    locale:

    #
    # SECURITY WARNING: it is CRITICAL that this file & directory are NOT accessible directly via a web browser!
    #
    # If you don't protect this directory from direct web access, anybody will be able to see your passwords.
    # http://nette.org/security-warning
    #
    
common:
        
            application:
                errorPresenter: Error

            database:
                dsn: 'mysql:host=localhost;dbname=quickstart'
                user: root
                password: heslo

            session:
                expiration: 30 days


        

    production < common:

    development < common:
    