services:
    authenticator: Todo\Authenticator
    routerFactory: RouterFactory
    router: @routerFactory::createRouter

    taskRepository: Todo\TaskRepository
    userRepository: Todo\UserRepository
    listRepository: Todo\ListRepository


factories:
